#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes/attributes.yaml
controllers:
    resource:
        path: ../src/UI/Http/Action/
        namespace: UI\Http\Action
    type: attribute
