services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tests\Acceptance\:
        resource: '../tests/Acceptance/*'

    Application\CommandHandler\:
        resource: '../src/Application/CommandHandler/*'
        public: true

    Application\QueryHandler\:
        resource: '../src/Application/QueryHandler/*'
        public: true
        
    Infra\Symfony6\Service\CommentIdGenerator:
        public: true
